### ISSUE TITLE
A huuuuuuuuuuuuge issue

### ISSUE THREAD

**Issue by hazzik** [FransBouma/RawDataAccessBencher#36]
I was trying to run this project to investigate a poor performance of some ORM. But the project does not compile.  I've expanded the error window which illustrates that there's something seriously wrong: 6K errors and 7 warnings.

There are many projects which compile and run just after simply cloning the repository. All of my projects compile and run after you clone a repo. I created a new project in VS just to demonstrate that a new project compiles and runs perfectly. 

![image](https://user-images.githubusercontent.com/144791/33068333-c9d8806e-cf15-11e7-9217-8cbeb9db94fc.png)

I feel a depression now and want to kill myself because I think I'm stupid.

Let's face it. I think with this level of compiling errors the project's repository must simply be removed from the Github to prevent hurting anyone's mental health.

**Comment by hazzik** [comment]
It's been almost an hour since I've filled this issue, why isn't it fixed yet? I'm honestly reporting an issue in your code which you (IMHO) should look into.

**Comment by FransBouma** [comment]
Let's ignore the childish behavior of you, for a second.

It looks like a couple of botched references in the nuget packages / csprojs. I updated a lot of packages the last time around, it looks like some csproj's refer to dlls on the system according to vs, while they are installed through nuget. Will correct them

**Comment by hazzik** [comment]
I won't bother you with any future issues ever again. That was a mistake, it seems. Well, lesson learned.

**Comment by MihaMarkic** [comment]
@hazzik As an external observer I agree with @FransBouma that your behavior is simply childish.

**Comment by wattengard** [comment]
So I guess I won't be using or recommending NHibernate anytime soon...

**Comment by FransBouma** [comment]
@hazzik 
> I won't bother you with any future issues ever again. That was a mistake, it seems. Well, lesson learned.

Dude, you're only cutting yourself with these kind of lame remarks. You're not 12, so act like the grown up you pretend to be. 

The issue you reported is legit however, so I'll fix that.

**Comment by hazzik** [comment]
It seems that you don't realize that everything here is _your_ words. Slightly reworded to suite the issue being reported.

**Comment by FransBouma** [comment]
@hazzik Oh of course I realize that, well, not that I say those words, but I did see you tried to copy some phrases. I also understand the concept of 'context', in which I said those, and the posts I replied to with those words, which were all in a conversation with you. A conversation you now deleted btw. 

The issue you ran into is because of some reference being bad. I fixed one, there's another with spatial types which I have to look into because the nuget package is referenced but apparently it doesn't pull it down. Is that equal to the performance of NHibernate when you compare v4.1 with v5, in severity? Seems likely, right?

Oh, and please, I did choose my words carefully in my opening post you are so angry about, I didn't use any lame words, I made it very clear it was something I ran into and thought you should *know*. I also gave it in the context of comparing v4.1 with v5 performance, and gave a screenshot of a profile session to give some insights what it might be. 

I didn't pressure you to fix it quickly, I didn't state your code sucks or any of that. I just gave you information that something is wrong, as the performance fell dramatically, comparing v4.1 with v5. You saw that as something compared to LLBLGen Pro, but where in the post do I even mention my own work? I didn't, as it has no relation to it. You made it a comparison between the two. 

Instead of saying "Hmm, that's indeed odd, we'll look into it", you came with all kinds of excuses like I misused NHibernate, I did something only a lamer would do, I didn't understand NHibernate, and it deteriorated from there. 

The last post in that conversion now states "You're really annoying, @FransBouma". Yes, people reporting issues you don't want to see, often are. But guess what, I can also not report it, leave it to your users who leave your work every day to find out the hard way.

**Comment by hazzik** [comment]
@FransBouma do you actually have any other than 'ad hominem' arguments?

**Comment by FransBouma** [comment]
@hazzik 
> do you actually have any other than 'ad hominem' arguments?

arguments to argue for what point exactly?

**Comment by hazzik** [comment]
>but where in the post do I even mention my own work? 

Yes, you did. I don't have proof, but you've said something like "the benchmark I've wrote to meause how my tool is doing better than others" (this is not exact quote, just from memory).

**Comment by hazzik** [comment]
Frans, not I started putting names and acusing others of childish behaviour, putting head into sand and better doing something to resolve issue. I never said anything about you personally. I as opposite, said that I'm not better than Fabio, implying that Fabio was a bad guy. 

What I was trying to say is that fetching many thousands of rows in one go is a known performance issue of NHibernate and should be avoided. But, no, you've started pushing that it's a legitime usage, because _other_ ORMs do support so. 

Just thinkg about that: if you've come to different people and those people behave the same when you report some issues, maybe it is somethiing wrong with you, and not with thoese people.

**Comment by hazzik** [comment]
Please stope lebelling people, and then, probably, other people will react to your queries appropriately.

**Comment by hazzik** [comment]
Just do "Update-Package -reinstall" in Package Management Console. It will fix all nuget references.  

There is also a forgotten reference to an ORM (Oak or something) that you've removed a couple of commits ago.

**Comment by FransBouma** [comment]
Sigh. 

@hazzik 
> Yes, you did. I don't have proof, but you've said something like "the benchmark I've wrote to meause how my tool is doing better than others" (this is not exact quote, just from memory).

Yes, I wrote the benchmarks to test how my code performed compared to the competition. I think that's common sense. How else would I know how it performed? I first didn't publish the results but after so many people stated EF was great I published them, with the code, so people could see for themselves. I included NHibernate to be complete. For the record, years ago my work didn't do so well. I spent a lot of time optimizing it so it would be on par with others. I also helped other frameworks get better. E.g. the ServiceStack OrmLite was slow at first and as I know the dev who wrote it and he's a nice guy I helped him out where the painpoints were, gave him a hint what to do and now it's very fast, faster than my work. 

You assume the worst of me but that's unfounded. 

> Frans, not I started putting names and acusing others of childish behaviour, putting head into sand and better doing something to resolve issue. I never said anything about you personally. I as opposite, said that I'm not better than Fabio, implying that Fabio was a bad guy.

Yes you did, like in the deleted posts in the NH repo. How I always come in saying 'LLBLGen can do a million joins and your code sucks' etc. 

> What I was trying to say is that fetching many thousands of rows in one go is a known performance issue of NHibernate and should be avoided. But, no, you've started pushing that it's a legitime usage, because other ORMs do support so.

I never heard anything like that's a known issue of NHibernate. Why not mention it in the first place? And you keep insisting I did this on purpose, but that's not the case. I simply picked a case to test fetch / materialization performance. That the results don't match what you wanted to see is understandable, but even so, you can't deny the performance degradation from v4.1 is big. In v4.1 you were faster than EF6, still nothing to write home about but alas, faster. 

> Just thinkg about that: if you've come to different people and those people behave the same when you report some issues, maybe it is somethiing wrong with you, and not with thoese people.

Where in the opening post did I do anything wrong? I wrote a piece of text where I carefully chose my words because I didn't want to offend anyone, I didn't mention any of my commercial work etc, just wanted to point something out, which you might not know. If you would know, e.g. it was already reported, just point me to it, case closed. 

Instead, things derailed rather quickly, with the usual excuses and mitigating factors, which are besides the point, and I hope you now understand why. 

> Just do "Update-Package -reinstall" in Package Management Console. It will fix all nuget references.
> There is also a forgotten reference to an ORM (Oak or something) that you've removed a couple of commits ago.

yes updating packages fixes most issues now, I corrected one reference, but there's still a problem with the spatial types package. 

Oak was removed a couple of commits ago indeed, it's odd vs left the reference there AND still compiled fine... I've removed it now.

**Comment by FransBouma** [comment]
Fixed

**Comment by hazzik** [comment]
You're quoting some posts which were accidentally corrupted by Grammarly and posted here and immediately deleted. "I as opposite, " was a glitch and should not start the sentence which it starts. There are a couple of sentences missing and it changed a meaning of that sentence completely.  I don't remember what I was going to say with "I as opposite", but the other part shall be "said that I'm not better than Fabio, implying that Fabio was a bad guy."

Yes, indeed I said, that you come and say that other people's code and tools sux. But you do this with "carefully choosing words". Like you've said several times "I don't want to say that your code bad" (not a direct quote) implying the opposite. Yes, I said that but **only after you** accused me being worse than Fabio (he's not a bad guy, btw), doing nothing to resolve this issue and hiding in the sand (but I've been working hard to solve the issue), never using the profiler, being unprofessional and etc. You've deserved this. And this is a long time observation of your behaviour. 

I never attack first, but I'm not a Jesus to turn my second cheek - I'll punch in return.  If you mess with me, you'll get twice as much.

At this point  I consider the issue closed for myself, do not need to reply further - I will no read anwers nor respond in return.

@MihaMarkic @wattengard you can do and think whatever you please, but your opinions do not matter here. Comments from strangers do not add any value.  Мимокрокодилы не нужны.

**Comment by FransBouma** [comment]
Cleaned up the thread as @hazzik has cleaned up his posts too.
